### ISSUE TITLE
Units missing in description

### ISSUE THREAD

**Issue by giannou** [giannou/OPEN-PROM#6]
https://github.com/giannou/OPEN-PROM/blob/70db4716cce28867d5f6d4cd8aa040acea7bd42d/declarations.gms#L61

https://github.com/giannou/OPEN-PROM/blob/70db4716cce28867d5f6d4cd8aa040acea7bd42d/declarations.gms#L62

Please fix this

**Comment by riazis** [comment]
No Units in the prototype. How to handle this? I asked Panagiotis and told me to ask you. Unit is missing in equation as in the variable
